### Task 1

In [1]:
import numpy as np

# Function to convert Fahrenheit to Celsius
def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5 / 9

# Create a numpy vectorized version of the function
vectorized_f_to_c = np.vectorize(fahrenheit_to_celsius)

# List of temperatures in Fahrenheit
temperatures_fahrenheit = [32, 68, 100, 212, 77]

# Apply the vectorized function to the list
temperatures_celsius = vectorized_f_to_c(temperatures_fahrenheit)

print(temperatures_celsius)


[  0.          20.          37.77777778 100.          25.        ]


### Task 2


In [7]:


# Custom function to calculate the power
def calculate_power(base, exponent):
    return base ** exponent

# Create a numpy vectorized version of the function
vectorized_power = np.vectorize(calculate_power)

# Arrays of numbers and powers
bases = [2, 3, 4, 5]
exponents = [1, 2, 3, 4]

# Apply the vectorized function to the arrays
result = vectorized_power(bases, exponents)

print(result)


[  2   9  64 625]


### Task 3

In [6]:


# Coefficient matrix
A = np.array([[4, 5, 6],
              [3, -1, 1],
              [2, 1, -2]])

# Constants matrix
B = np.array([7, 4, 5])

# Solve the system of equations
solution = np.linalg.solve(A, B)

print(solution)


[ 1.7027027   0.62162162 -0.48648649]


### Task 4


In [24]:
import numpy as np
from PIL import Image
import os
import random
# Coefficient matrix
A = np.array([[10, -2, 3],
              [-2, 8, -1],
              [3, -1, 6]])

# Constants matrix
B = np.array([12, -5, 15])

# Solve the system of equations
currents = np.linalg.solve(A, B)

print(currents)  # This will print the values of I1, I2, and I3




[ 0.48963731 -0.2253886   2.21761658]


In [36]:
import numpy as np
from PIL import Image
import os
import random

# Ensure that the 'images' folder exists or provide the correct path
image_path = "images/birds.jpg"

# Check if the file exists before opening
if os.path.exists(image_path):
    # Read the image using PIL
    img = Image.open(image_path)
    img_array = np.array(img)

    # Function to flip the image horizontally and vertically
    def flip_image(img_array):
        return np.flipud(np.fliplr(img_array))

    # Function to add random noise to the image
    def add_noise(img_array, noise_factor=0.1):
        noise = np.random.randn(*img_array.shape) * noise_factor * 255
        noisy_image = img_array + noise
        return np.clip(noisy_image, 0, 255).astype(np.uint8)

    # Function to brighten the channels (e.g., red channel)
    def brighten_channels(img_array, increase_value=40):
        img_array = img_array.astype(np.int16)  # Use int16 to avoid overflow
        img_array[:, :, 0] += increase_value  # Increase red channel
        return np.clip(img_array, 0, 255).astype(np.uint8)

    # Function to apply a mask to a rectangular region
    def apply_mask(img_array, mask_size=(100, 100), top_left=(img_array.shape[0]//2 - 50, img_array.shape[1]//2 - 50)):
        mask = img_array.copy()
        x_start, y_start = top_left
        x_end, y_end = x_start + mask_size[0], y_start + mask_size[1]
        mask[x_start:x_end, y_start:y_end] = [0, 0, 0]  # Set pixels to black
        return mask

    # Perform the image manipulations
    flipped_image = flip_image(img_array)
    noisy_image = add_noise(flipped_image)
    brightened_image = brighten_channels(noisy_image)
    masked_image = apply_mask(brightened_image)

    # Convert the numpy array back to an image using PIL and save it
    final_image = Image.fromarray(masked_image)
    final_image.save("images/modified_birds.jpg")

    print("Image manipulation complete and saved to 'images/modified_birds.jpg'")

else:
    print(f"Error: The file '{image_path}' does not exist. Please check the path.")


Image manipulation complete and saved to 'images/modified_birds.jpg'
