### task 1


In [3]:
import numpy as np

vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### task 2


In [5]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### task 3


In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### task 4

In [7]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.39220343 0.63418722 0.91398828]
  [0.83371805 0.81273372 0.36090169]
  [0.30214404 0.08996961 0.82439219]]

 [[0.38905647 0.89987311 0.40308551]
  [0.86541008 0.09240264 0.86405112]
  [0.09375786 0.98168517 0.83567484]]

 [[0.03312093 0.22879443 0.09450839]
  [0.53333559 0.90001379 0.98408007]
  [0.80814924 0.01163608 0.6250861 ]]]


### task 5


In [8]:
random_array = np.random.random((10, 10))

# Finding min and max values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random 10x10 array:\n", random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 array:
 [[0.05956566 0.08741919 0.59490787 0.55248661 0.88842837 0.91756011
  0.05056103 0.54039319 0.56139129 0.06455964]
 [0.35608845 0.11644532 0.31365866 0.01418488 0.62970169 0.76185358
  0.14761335 0.59598868 0.83170571 0.10850083]
 [0.6185716  0.96869757 0.72034024 0.3766598  0.20876975 0.55734126
  0.55135257 0.305018   0.45306383 0.50652237]
 [0.67171459 0.16680336 0.33559412 0.88081461 0.11436422 0.0900887
  0.01101564 0.55487317 0.38472095 0.83779915]
 [0.21843282 0.32726917 0.13439793 0.22297798 0.86894578 0.90624965
  0.64832083 0.83568892 0.60483256 0.58024218]
 [0.12676722 0.67620208 0.34601342 0.04358171 0.31405033 0.82808517
  0.00723705 0.32649767 0.76830651 0.31246892]
 [0.1483587  0.76224104 0.01698831 0.012359   0.23775018 0.41018037
  0.3006904  0.83878829 0.57193807 0.47185791]
 [0.06827085 0.51290563 0.37448506 0.49007127 0.63658745 0.50575839
  0.24328155 0.82399742 0.55671295 0.00708526]
 [0.76681125 0.16353457 0.47434671 0.44206872 0.08463323 0.4

### task 6


In [9]:
random_vector = np.random.random(30)


mean_value = np.mean(random_vector)

print("Random vector:\n", random_vector)
print("\nMean value:", mean_value)


Random vector:
 [0.35155426 0.4510894  0.82558301 0.01549652 0.18058633 0.66328768
 0.22126956 0.78909588 0.57290412 0.64994355 0.64938277 0.27664145
 0.86512108 0.09538084 0.05931165 0.90073776 0.84733428 0.26127629
 0.47046531 0.92988917 0.60821598 0.4343799  0.87046892 0.77353954
 0.54908136 0.84573088 0.2565153  0.58987734 0.33360311 0.22599132]

Mean value: 0.5187918189540804


### task7

In [10]:
matrix = np.random.random((5, 5))

# Normalizing the matrix
norm_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Original matrix:\n", matrix)
print("\nNormalized matrix:\n", norm_matrix)


Original matrix:
 [[0.60004023 0.18281081 0.4183599  0.55217535 0.27256449]
 [0.6017779  0.79725947 0.56047506 0.78377716 0.12674292]
 [0.33973529 0.03679406 0.44069808 0.87775474 0.17253015]
 [0.12248469 0.02997588 0.81571481 0.2160708  0.79101496]
 [0.1676021  0.02851248 0.67399005 0.70820406 0.13338469]]

Normalized matrix:
 [[0.67298553 0.18168942 0.45905326 0.61662366 0.2873762 ]
 [0.67503167 0.90521519 0.62639674 0.88933949 0.11566834]
 [0.36647118 0.00975173 0.48535692 1.         0.16958373]
 [0.1106542  0.00172319 0.92694672 0.22085373 0.89786215]
 [0.16378085 0.         0.76006294 0.80035063 0.12348916]]


### task 8

In [11]:
A = np.random.random((5, 3))

# Creating a 3x2 matrix with random values
B = np.random.random((3, 2))

# Matrix multiplication (dot product)
C = np.dot(A, B)

print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nResulting Matrix C (5x2):\n", C)


Matrix A (5x3):
 [[0.56432294 0.0199003  0.38483431]
 [0.70514924 0.26165401 0.5698361 ]
 [0.39214006 0.69345024 0.06912675]
 [0.57199112 0.25451743 0.25860234]
 [0.35457689 0.41929103 0.03242411]]

Matrix B (3x2):
 [[0.4348381  0.30552969]
 [0.13261027 0.12047425]
 [0.07724528 0.96573559]]

Resulting Matrix C (5x2):
 [[0.27775474 0.54646307]
 [0.38534091 0.7972776 ]
 [0.26781578 0.27011149]
 [0.30245097 0.45516454]
 [0.21229045 0.19016065]]


### task 9

In [12]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Computing the dot product
C = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot Product (A * B):\n", C)


Matrix A:
 [[0.3766694  0.68462411 0.58904232]
 [0.9591085  0.10188724 0.42066871]
 [0.5931688  0.4742994  0.26368187]]

Matrix B:
 [[0.12991668 0.75749804 0.51023884]
 [0.29823151 0.60512571 0.22386394]
 [0.44109336 0.59537593 0.85942758]]

Dot Product (A * B):
 [[0.51293477 1.0503116  0.85169322]
 [0.34054435 1.03863342 0.87371759]
 [0.33482187 0.8933248  0.63545177]]


### task 10


In [13]:
A = np.random.random((4, 4))

# Computing the transpose
A_transpose = A.T

print("Original Matrix (A):\n", A)
print("\nTranspose of Matrix (A^T):\n", A_transpose)

Original Matrix (A):
 [[0.71825957 0.74676841 0.28531707 0.15643017]
 [0.20622713 0.66832151 0.42851637 0.96891164]
 [0.12227581 0.6773098  0.89204063 0.14545271]
 [0.02726848 0.92016044 0.75902502 0.70996806]]

Transpose of Matrix (A^T):
 [[0.71825957 0.20622713 0.12227581 0.02726848]
 [0.74676841 0.66832151 0.6773098  0.92016044]
 [0.28531707 0.42851637 0.89204063 0.75902502]
 [0.15643017 0.96891164 0.14545271 0.70996806]]


### task 11


In [14]:

A = np.random.randint(1, 10, (3, 3))

# Computing the determinant
det_A = np.linalg.det(A)

print("Matrix (A):\n", A)
print("\nDeterminant of A:", det_A)


Matrix (A):
 [[2 6 7]
 [4 8 4]
 [2 4 3]]

Determinant of A: -7.999999999999998


### task 12


In [15]:
A = np.random.randint(1, 10, (3, 4))

# Creating a 4x3 matrix (B)
B = np.random.randint(1, 10, (4, 3))

# Computing the matrix product A · B
C = np.dot(A, B)

print("Matrix A (3x4):\n", A)
print("\nMatrix B (4x3):\n", B)
print("\nMatrix Product A · B (3x3):\n", C)


Matrix A (3x4):
 [[5 8 9 2]
 [9 9 3 6]
 [2 1 2 4]]

Matrix B (4x3):
 [[6 7 7]
 [6 3 8]
 [5 1 5]
 [9 1 4]]

Matrix Product A · B (3x3):
 [[141  70 152]
 [177  99 174]
 [ 64  23  48]]


### task 13


In [16]:
A = np.random.randint(1, 10, (3, 3))

# Creating a 3-element column vector
v = np.random.randint(1, 10, (3, 1))

# Computing the matrix-vector product
result = np.dot(A, v)

print("Matrix A (3x3):\n", A)
print("\nColumn Vector v (3x1):\n", v)
print("\nMatrix-Vector Product A · v (3x1):\n", result)


Matrix A (3x3):
 [[8 9 2]
 [1 8 1]
 [1 2 4]]

Column Vector v (3x1):
 [[2]
 [3]
 [3]]

Matrix-Vector Product A · v (3x1):
 [[49]
 [29]
 [20]]


### task 14

In [17]:

A = np.random.randint(1, 10, (3, 3))

# Creating a random 3x1 column vector
b = np.random.randint(1, 10, (3, 1))

# Solving for x in Ax = b
try:
    x = np.linalg.solve(A, b)
    print("Matrix A (3x3):\n", A)
    print("\nColumn Vector b (3x1):\n", b)
    print("\nSolution x (3x1):\n", x)
except np.linalg.LinAlgError:
    print("Matrix A is singular and cannot be inverted.")


Matrix A (3x3):
 [[8 7 9]
 [2 9 4]
 [2 6 9]]

Column Vector b (3x1):
 [[1]
 [4]
 [8]]

Solution x (3x1):
 [[-1.21385542]
 [ 0.28313253]
 [ 0.96987952]]


### task 15

In [18]:
A = np.random.randint(1, 10, (5, 5))

# Compute row-wise sums
row_sums = np.sum(A, axis=1)

# Compute column-wise sums
col_sums = np.sum(A, axis=0)

# Print results
print("Matrix A (5x5):\n", A)
print("\nRow-wise sums:\n", row_sums)
print("\nColumn-wise sums:\n", col_sums)


Matrix A (5x5):
 [[3 2 3 5 8]
 [3 7 5 9 9]
 [9 6 2 8 1]
 [5 1 8 2 1]
 [9 8 4 9 8]]

Row-wise sums:
 [21 33 26 17 38]

Column-wise sums:
 [29 24 22 33 27]
