### task 1


In [1]:
import numpy as np

vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### task 2


In [2]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### task 3


In [3]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### task 4

In [23]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.17508134 0.0945762  0.01492582]
  [0.41722377 0.43613629 0.44705437]
  [0.50871683 0.66673479 0.89675112]]

 [[0.49263753 0.76238426 0.60228784]
  [0.7524227  0.26139237 0.73322728]
  [0.39809246 0.59147642 0.16991216]]

 [[0.00756372 0.52155432 0.8113618 ]
  [0.8902392  0.05141071 0.95528585]
  [0.75610938 0.31809067 0.79493198]]]


### task 5


In [24]:
random_array = np.random.random((10, 10))

# Finding min and max values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random 10x10 array:\n", random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 array:
 [[0.55929724 0.30160912 0.58858747 0.96900097 0.2029184  0.53450711
  0.30789882 0.79740927 0.6669922  0.78594799]
 [0.25579156 0.86831536 0.50674433 0.37788477 0.16778354 0.55247238
  0.70832231 0.78178362 0.29851738 0.4054931 ]
 [0.29734746 0.62477728 0.1217392  0.60335985 0.20545374 0.47941501
  0.6603671  0.59759338 0.13121192 0.71778985]
 [0.47962909 0.82615187 0.07585405 0.49142574 0.44901408 0.91512973
  0.47852051 0.53512039 0.12766512 0.10472609]
 [0.89966994 0.5594434  0.83052552 0.63762726 0.93158312 0.79815375
  0.48394173 0.90063269 0.57623167 0.87514525]
 [0.16260659 0.8861678  0.97309632 0.10945504 0.02421981 0.54162119
  0.42458038 0.25198053 0.04704532 0.45959954]
 [0.94471895 0.59642156 0.37487482 0.07212182 0.33834979 0.8677085
  0.74163876 0.25648849 0.44473158 0.17524747]
 [0.90331626 0.5257572  0.34391476 0.63439421 0.48191338 0.20404998
  0.32949374 0.40020361 0.54270671 0.13994337]
 [0.48870745 0.088998   0.58499792 0.33293357 0.32844929 0.8

### task 6


In [25]:
random_vector = np.random.random(30)


mean_value = np.mean(random_vector)

print("Random vector:\n", random_vector)
print("\nMean value:", mean_value)


Random vector:
 [8.15323820e-01 5.62954936e-01 9.62790328e-01 4.71288422e-01
 9.33410285e-01 5.28616593e-01 7.57286982e-01 1.69877459e-02
 9.13923641e-01 5.02843356e-02 7.20984262e-01 6.50097074e-01
 4.48859958e-01 2.87985185e-01 6.08535389e-01 1.38772657e-01
 7.57083546e-01 8.53035186e-01 7.40723278e-01 8.58770837e-01
 5.61002559e-01 2.99703445e-01 7.46325123e-01 8.13118545e-01
 9.13020042e-04 6.67392128e-01 6.06272466e-01 6.48825561e-02
 3.73414389e-01 6.42111653e-01]

Mean value: 0.5617616781546133


### task7

In [19]:
matrix = np.random.random((5, 5))

# Normalizing the matrix
norm_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
var = norm_matrix != 0
print("Original matrix:\n", matrix)
print("\nNormalized matrix:\n", norm_matrix)


Original matrix:
 [[0.85599958 0.90181139 0.76388542 0.46809675 0.38573502]
 [0.50039413 0.18673585 0.05166536 0.61107506 0.69809961]
 [0.12330629 0.36464558 0.85951281 0.5366845  0.52486969]
 [0.31019238 0.46454656 0.38715513 0.22275318 0.0367084 ]
 [0.20960795 0.3149323  0.91202664 0.16025665 0.98524854]]

Normalized matrix:
 [[0.86373906 0.91203624 0.76662757 0.45479187 0.36796188]
 [0.48884144 0.15816669 0.0157684  0.60552699 0.69727277]
 [0.09129597 0.34572831 0.8674429  0.52710062 0.51464484]
 [0.28832093 0.45104909 0.36945904 0.19613801 0.        ]
 [0.18227964 0.29331801 0.92280568 0.13025094 1.        ]]


### task 8

In [11]:
A = np.random.random((5, 3))

# Creating a 3x2 matrix with random values
B = np.random.random((3, 2))

# Matrix multiplication (dot product)
C = np.dot(A, B)

print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nResulting Matrix C (5x2):\n", C)


Matrix A (5x3):
 [[0.56432294 0.0199003  0.38483431]
 [0.70514924 0.26165401 0.5698361 ]
 [0.39214006 0.69345024 0.06912675]
 [0.57199112 0.25451743 0.25860234]
 [0.35457689 0.41929103 0.03242411]]

Matrix B (3x2):
 [[0.4348381  0.30552969]
 [0.13261027 0.12047425]
 [0.07724528 0.96573559]]

Resulting Matrix C (5x2):
 [[0.27775474 0.54646307]
 [0.38534091 0.7972776 ]
 [0.26781578 0.27011149]
 [0.30245097 0.45516454]
 [0.21229045 0.19016065]]


### task 9

In [12]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Computing the dot product
C = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot Product (A * B):\n", C)


Matrix A:
 [[0.3766694  0.68462411 0.58904232]
 [0.9591085  0.10188724 0.42066871]
 [0.5931688  0.4742994  0.26368187]]

Matrix B:
 [[0.12991668 0.75749804 0.51023884]
 [0.29823151 0.60512571 0.22386394]
 [0.44109336 0.59537593 0.85942758]]

Dot Product (A * B):
 [[0.51293477 1.0503116  0.85169322]
 [0.34054435 1.03863342 0.87371759]
 [0.33482187 0.8933248  0.63545177]]


### task 10


In [13]:
A = np.random.random((4, 4))

# Computing the transpose
A_transpose = A.T

print("Original Matrix (A):\n", A)
print("\nTranspose of Matrix (A^T):\n", A_transpose)

Original Matrix (A):
 [[0.71825957 0.74676841 0.28531707 0.15643017]
 [0.20622713 0.66832151 0.42851637 0.96891164]
 [0.12227581 0.6773098  0.89204063 0.14545271]
 [0.02726848 0.92016044 0.75902502 0.70996806]]

Transpose of Matrix (A^T):
 [[0.71825957 0.20622713 0.12227581 0.02726848]
 [0.74676841 0.66832151 0.6773098  0.92016044]
 [0.28531707 0.42851637 0.89204063 0.75902502]
 [0.15643017 0.96891164 0.14545271 0.70996806]]


### task 11


In [14]:

A = np.random.randint(1, 10, (3, 3))

# Computing the determinant
det_A = np.linalg.det(A)

print("Matrix (A):\n", A)
print("\nDeterminant of A:", det_A)


Matrix (A):
 [[2 6 7]
 [4 8 4]
 [2 4 3]]

Determinant of A: -7.999999999999998


### task 12


In [15]:
A = np.random.randint(1, 10, (3, 4))

# Creating a 4x3 matrix (B)
B = np.random.randint(1, 10, (4, 3))

# Computing the matrix product A · B
C = np.dot(A, B)

print("Matrix A (3x4):\n", A)
print("\nMatrix B (4x3):\n", B)
print("\nMatrix Product A · B (3x3):\n", C)


Matrix A (3x4):
 [[5 8 9 2]
 [9 9 3 6]
 [2 1 2 4]]

Matrix B (4x3):
 [[6 7 7]
 [6 3 8]
 [5 1 5]
 [9 1 4]]

Matrix Product A · B (3x3):
 [[141  70 152]
 [177  99 174]
 [ 64  23  48]]


### task 13


In [16]:
A = np.random.randint(1, 10, (3, 3))

# Creating a 3-element column vector
v = np.random.randint(1, 10, (3, 1))

# Computing the matrix-vector product
result = np.dot(A, v)

print("Matrix A (3x3):\n", A)
print("\nColumn Vector v (3x1):\n", v)
print("\nMatrix-Vector Product A · v (3x1):\n", result)


Matrix A (3x3):
 [[8 9 2]
 [1 8 1]
 [1 2 4]]

Column Vector v (3x1):
 [[2]
 [3]
 [3]]

Matrix-Vector Product A · v (3x1):
 [[49]
 [29]
 [20]]


### task 14

In [17]:

A = np.random.randint(1, 10, (3, 3))

# Creating a random 3x1 column vector
b = np.random.randint(1, 10, (3, 1))

# Solving for x in Ax = b
try:
    x = np.linalg.solve(A, b)
    print("Matrix A (3x3):\n", A)
    print("\nColumn Vector b (3x1):\n", b)
    print("\nSolution x (3x1):\n", x)
except np.linalg.LinAlgError:
    print("Matrix A is singular and cannot be inverted.")


Matrix A (3x3):
 [[8 7 9]
 [2 9 4]
 [2 6 9]]

Column Vector b (3x1):
 [[1]
 [4]
 [8]]

Solution x (3x1):
 [[-1.21385542]
 [ 0.28313253]
 [ 0.96987952]]


### task 15

In [18]:
A = np.random.randint(1, 10, (5, 5))

# Compute row-wise sums
row_sums = np.sum(A, axis=1)

# Compute column-wise sums
col_sums = np.sum(A, axis=0)

# Print results
print("Matrix A (5x5):\n", A)
print("\nRow-wise sums:\n", row_sums)
print("\nColumn-wise sums:\n", col_sums)


Matrix A (5x5):
 [[3 2 3 5 8]
 [3 7 5 9 9]
 [9 6 2 8 1]
 [5 1 8 2 1]
 [9 8 4 9 8]]

Row-wise sums:
 [21 33 26 17 38]

Column-wise sums:
 [29 24 22 33 27]
